In [56]:
import numpy as np

# **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [58]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [22]:
#Математика неумолима. Разной формы получается только 4 массива
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(3, 4)

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [23]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 4)
b5 = a.reshape(-1, 6)

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Так и называем

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.
    Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [45]:
import random
c = np.random.randn(3,4)
c

array([[-1.86571963,  0.63085565,  0.79448174,  0.42120984],
       [-1.33494457, -1.56744165,  1.24289574,  1.19801922],
       [-1.30642071,  0.23091736,  0.81916975,  0.99448853]])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [61]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
В чем разница между массивами a и b?

In [62]:
b = a.reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

a - одномерный, b - двумерный. Вот и вся разница

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.



In [70]:
b = np.ones((3,2))
a = np.zeros((2,2))
v = np.vstack((a, b))
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?



In [82]:
a = np.arange(0, 12, 1)
# поменять форму этого массива, чтобы получилась матрица А (двумерный массив Numpy), 4x3
A = a.reshape(4, -1)
# получить матрицу At
At = A.T
# помножить A и At, вывести размер 
B = At.dot(A)
B.size
# обратную матрицу для В не посчитать, потому что ее определитель !=0
d = np.linalg.det(B)
print(d)

-1.5347723092418012e-11


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [83]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [84]:
c = np.random.randint(0, 16, (1, 16))

print(c)

[[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [ ]:
C = c.reshape(4,4)
# Матрица B имеет размер 3х3, матрица С имеет размер 4х4. Потому сложить их не выйдет