# Урок 2 часть 1. ПЗ

**1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:**

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

Кол-во столбцов первой матрицы == кол-ву строк второй матрицы
в) умножению подлежит. получена матрица размерности 8х8
г) умножению подлежит. получена матрица размерности 4х4

**2. Найти сумму и произведение матриц**

In [ ]:
import numpy as np

In [12]:
A=np.array([[1, -2],
    [3, 0]])
B=np.array([[4, -1],
   [0, 5]])

In [13]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [14]:
A * B

array([[4, 2],
       [0, 0]])

**3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, 
что матрицы одного размера образуют линейное пространство.**
Вычислить линейную комбинацию  3A−2B+4C  для матриц  A=(137−6) ,  B=(025−1) ,  C=(21−41). 

In [19]:
A = np.array([[1, 3], [7, -6]])
B = np.array([[0, 2], [5, -1]])
C = np.array([[2, 1], [-4, 1]])

3*A-2*B+4*C

array([[ 11,   9],
       [ -5, -12]])

**4. Дана матрица  A. Вычислить  AAT  и  ATA .**

In [27]:
A = np.array([[4, 5], [2, 1], [2, 3]])
AT = A.transpose()
C = A.dot(AT)
C

array([[41, 13, 23],
       [13,  5,  7],
       [23,  7, 13]])

# Урок 2, часть 2, ПЗ

**1. Вычислить определитель:**

In [10]:
import math

In [ ]:
a) detA = sin(x)**2 + cos(x)**2 = 1

In [6]:
#б)
detA = 4*5*9
detA

180

In [ ]:
# Вследствие линейной зависимости строк
detA = 0

**2. Определитель матрицы  A  равен  4 . Найти:**

**согласно свойствам определителей матриц**
а)  det(A2) = 16;

б)  det(AT) = 4;

в)  det(2A) = ??.

# 3.Доказать, что матрица является вырожденной
Найдем определитель и надеемся, что он равен нулю

In [14]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
detA = np.linalg.det(A)
detA

0.0

**Вычислить ранг матрицы**

In [16]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
rank = np.linalg.matrix_rank(A)
rank

2

In [17]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
rank = np.linalg.matrix_rank(B)
rank

3